export type FishingFishRarity = "common" | "uncommon" | "rare" | "epic" | "legendary";

export const FISHING_FISH = [
  {
    id: "silver-creek-carp",
    name: "银溪鲫",
    rarity: "common",
    rarityLabel: "常见",
    price: 8,
    size: "8-16 cm",
    habitat: "浅水石滩",
    trait: "胆子小但很贪吃，适合新手练习抛竿。",
    image: "/assets/fishing/fish/silver-creek-carp.png",
  },
  {
    id: "peach-petal-fish",
    name: "桃鳞鱼",
    rarity: "common",
    rarityLabel: "常见",
    price: 12,
    size: "10-18 cm",
    habitat: "花瓣落水处",
    trait: "会追着花影游动，上钩时浮漂会轻轻连点两下。",
    image: "/assets/fishing/fish/peach-petal-fish.png",
  },
  {
    id: "bamboo-minnow",
    name: "青竹鱼",
    rarity: "uncommon",
    rarityLabel: "少见",
    price: 18,
    size: "12-22 cm",
    habitat: "芦苇和竹影边",
    trait: "游速很快，收线时张力条会来回摆动。",
    image: "/assets/fishing/fish/bamboo-minnow.png",
  },
  {
    id: "star-koi",
    name: "星点锦鲤",
    rarity: "rare",
    rarityLabel: "稀有",
    price: 32,
    size: "18-30 cm",
    habitat: "阳光照到的水面",
    trait: "鳞片像小星星，咬钩前水面会闪一下。",
    image: "/assets/fishing/fish/star-koi.png",
  },
  {
    id: "moon-loach",
    name: "月光鳅",
    rarity: "rare",
    rarityLabel: "稀有",
    price: 38,
    size: "15-26 cm",
    habitat: "桥影和深水边",
    trait: "喜欢贴着水底游，拉扯时间比普通鱼更长。",
    image: "/assets/fishing/fish/moon-loach.png",
  },
  {
    id: "cloud-bass",
    name: "云纹鲈",
    rarity: "epic",
    rarityLabel: "珍稀",
    price: 56,
    size: "22-36 cm",
    habitat: "荷叶和水草中",
    trait: "身上有云朵纹路，成功收线会额外给经验。",
    image: "/assets/fishing/fish/cloud-bass.png",
  },
  {
    id: "golden-koi",
    name: "金尾锦鲤",
    rarity: "epic",
    rarityLabel: "珍稀",
    price: 88,
    size: "25-42 cm",
    habitat: "清晨的主河道",
    trait: "金色尾巴很显眼，是高价值结算鱼。",
    image: "/assets/fishing/fish/golden-koi.png",
  },
  {
    id: "question-puffer",
    name: "问号河豚",
    rarity: "legendary",
    rarityLabel: "传说",
    price: 128,
    size: "12-20 cm",
    habitat: "随机问答水泡旁",
    trait: "出现概率很低，钓到后会解锁一条隐藏趣味描述。",
    image: "/assets/fishing/fish/question-puffer.png",
  },
] as const;
